title = "WF SICKNESS"

[database]
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"

sql_table_sickness = "wf_sickness"
sql_table_byreason = "wf_sickness_byreason"

sql_cooloff = 60

[struct]
data_dir = "data"
source_dir = "current"
archive_dir = "archive"

[map_files]
column_names = "./data/column_map.csv"
ics_lookup = "./docs/ics_lookup.sql"

[codes]
region_london = "Y56"

[data_scraping]
publication_name = "nhs-sickness-absence-rates"
target_files = ["NHS Sickness Absence benchmarking tool CSV", "NHS Sickness Absence by reason, staff group and organisation CSV"]