title = "WF SICKNESS"

[database]
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"

sql_table_sickness = "wf_sickness"
sql_table_byreason = "wf_byreason"

sql_cooloff = 60

["struct"]
data_dir = "data"
source_dir = "current"
archive_dir = "archive"



[map_files]
column_names = "./data/column_map.csv"

[codes]
region_london = "Y56"